"""
Clarification Agent - Generates questions to refine user's search query.

Uses GPT-5-mini to:
1. Generate 3 relevant clarification questions based on product keyword
2. Build a refined search query from user's answers

Example:
    agent = ClarificationAgent()
    questions = agent.generate_questions("laptop")
    # Q1: Brand preference? Q2: Use case? Q3: Budget?
    refined = agent.build_refined_query("laptop", questions, ["Acer", "for students", "under $800"])
    # refined.query = "Acer laptops for students under $800"
"""

import logging
from typing import List

from openai import OpenAI
from pydantic import BaseModel, Field


# ============================================================================
# PYDANTIC SCHEMAS
# ============================================================================

class ClarificationQuestion(BaseModel):
    """A single clarification question with options."""
    question: str = Field(description="The clarification question in English")
    options: List[str] = Field(
        description="4-6 options for the user to choose from. Last option should always be 'Any' or 'No preference'",
        min_length=3,
        max_length=6
    )


class ClarificationResponse(BaseModel):
    """Response containing clarification questions generated by LLM."""
    product_category: str = Field(
        description="Detected product category (e.g., 'laptop', 'TV', 'headphones')"
    )
    questions: List[ClarificationQuestion] = Field(
        description="Exactly 3 clarification questions to help refine the search",
        min_length=3,
        max_length=3
    )


class RefinedQuery(BaseModel):
    """Refined search query built from user answers."""
    query: str = Field(description="Optimized search query in English for product search")
    summary: str = Field(description="Brief summary of what the user is looking for")


# ============================================================================
# CLARIFICATION AGENT
# ============================================================================

class ClarificationAgent:
    """
    Agent that generates clarification questions before search.
    
    Uses GPT-5-mini to:
    1. Generate 3 relevant questions based on user's keyword
    2. Build a refined search query from user's answers
    
    Attributes:
        MODEL: OpenAI model to use (gpt-5-mini)
        openai: OpenAI client instance
    """
    
    MODEL = "gpt-5-mini"
    
    GENERATE_QUESTIONS_PROMPT = """You are a smart shopping assistant. When a user wants to search for a product, 
you need to ask 3 clarification questions to better understand their needs.

RULES:
1. Generate exactly 3 questions relevant to the product type
2. Each question should have 4-6 options
3. The last option should always be "Any" or "No preference"
4. Questions should cover different aspects like: brand, use case, budget, features, size, etc.
5. Adapt questions to the product category (laptop questions differ from skincare questions)
6. Keep questions concise and clear

EXAMPLES:
- For "laptop": Ask about brand preference, primary use (gaming/work/study), budget range
- For "TV": Ask about screen size, smart features, brand preference
- For "headphones": Ask about type (over-ear/in-ear), use case (music/gaming/calls), wireless preference
"""
    
    BUILD_QUERY_PROMPT = """Based on the user's original keyword and their answers to clarification questions,
build an optimized search query for product search on e-commerce sites.

RULES:
1. Query should be in English
2. Keep it concise - only include relevant keywords
3. If user answered "Any" or "No preference", skip that criterion
4. Include price constraint if user specified a budget (e.g., "under $800")
5. Focus on searchable terms that e-commerce sites would understand
"""
    
    def __init__(self):
        """Initialize with OpenAI client."""
        self.openai = OpenAI()
        logging.info("ClarificationAgent initialized with GPT-5-mini")
    
    def generate_questions(self, keyword: str) -> ClarificationResponse:
        """
        Generate 3 clarification questions based on user's keyword.
        
        Args:
            keyword: User's initial search keyword (e.g., "laptop")
            
        Returns:
            ClarificationResponse with 3 questions and options
        """
        logging.info(f"Generating clarification questions for: '{keyword}'")
        
        result = self.openai.chat.completions.parse(
            model=self.MODEL,
            messages=[
                {"role": "system", "content": self.GENERATE_QUESTIONS_PROMPT},
                {"role": "user", "content": f"Product keyword: {keyword}"}
            ],
            response_format=ClarificationResponse
        )
        
        response = result.choices[0].message.parsed
        logging.info(f"Generated {len(response.questions)} questions")
        return response
    
    def build_refined_query(
        self, 
        keyword: str, 
        questions: List[ClarificationQuestion],
        answers: List[str]
    ) -> RefinedQuery:
        """
        Build refined search query from user's answers.
        
        Args:
            keyword: Original keyword
            questions: List of questions that were asked
            answers: User's answers to each question
            
        Returns:
            RefinedQuery with optimized search string
        """
        logging.info("Building refined query...")
        
        # Format Q&A for the prompt
        qa_text = ""
        for i, (q, a) in enumerate(zip(questions, answers), 1):
            qa_text += f"Q{i}: {q.question}\nA{i}: {a}\n\n"
        
        user_message = f"""Original keyword: {keyword}

User's answers:
{qa_text}

Build an optimized search query based on these answers."""
        
        result = self.openai.chat.completions.parse(
            model=self.MODEL,
            messages=[
                {"role": "system", "content": self.BUILD_QUERY_PROMPT},
                {"role": "user", "content": user_message}
            ],
            response_format=RefinedQuery
        )
        
        refined = result.choices[0].message.parsed
        logging.info(f"Refined query: '{refined.query}'")
        return refined
