"""
BestBuy Deal Finder v2 - Gradio Web App with Clarification Flow

Enhanced version with chatbot-style clarification questions before search.

Supports 2 flows:
1. Clarification Flow: User answers 3 questions → Refined query → Better deals
2. Skip Flow: User skips questions → Search with original keyword

Workflow:
1. [NEW] Generate clarification questions (GPT-5-mini)
2. [NEW] Build refined query from answers OR skip
3. Search URLs (Brave MCP)
4. Filter sale items (BeautifulSoup)
5. Scrape details (Playwright)
6. Select top 5 deals (GPT-5-mini)
7. Estimate prices (EnsembleAgent: 3 models)
"""

import os
import sys
import logging
import queue
import threading
import time
import asyncio
from typing import List, Optional, Tuple

import gradio as gr
import chromadb
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from openai import OpenAI

# Import BestBuy modules
from price_agents.bestbuy_deals import (
    ScrapedBestBuyDeal,
    filter_sale_urls,
    scrape_bestbuy_products
)
from price_agents.bestbuy_scanner_agent import (
    BestBuySearchAgent,
    BestBuyScannerAgent
)

# Import existing agents
from price_agents.ensemble_agent import EnsembleAgent
from price_agents.messaging_agent import MessagingAgent
from price_agents.deals import Deal, DealSelection, Opportunity
from log_utils import reformat


# ============================================================================
# SECTION 1: SETUP & CONFIGURATION
# ============================================================================

# Load environment variables
load_dotenv(override=True)

# Setup logging
logging.basicConfig(level=logging.INFO)
root = logging.getLogger()
root.setLevel(logging.INFO)

# Database path
DB_PATH = "products_vectorstore"


# ============================================================================
# SECTION 2: PYDANTIC SCHEMAS FOR CLARIFICATION
# ============================================================================

class ClarificationQuestion(BaseModel):
    """A single clarification question with options."""
    question: str = Field(description="The clarification question in English")
    options: List[str] = Field(
        description="4-6 options for the user to choose from. Last option should always be 'Any' or 'No preference'",
        min_length=3,
        max_length=6
    )


class ClarificationResponse(BaseModel):
    """Response containing clarification questions generated by LLM."""
    product_category: str = Field(description="Detected product category (e.g., 'laptop', 'TV', 'headphones')")
    questions: List[ClarificationQuestion] = Field(
        description="Exactly 3 clarification questions to help refine the search",
        min_length=3,
        max_length=3
    )


class RefinedQuery(BaseModel):
    """Refined search query built from user answers."""
    query: str = Field(description="Optimized search query in English for BestBuy search")
    summary: str = Field(description="Brief summary of what the user is looking for")


# ============================================================================
# SECTION 3: CLARIFICATION AGENT
# ============================================================================

class ClarificationAgent:
    """
    Agent that generates clarification questions before search.
    
    Uses GPT-5-mini to:
    1. Generate 3 relevant questions based on user's keyword
    2. Build a refined search query from user's answers
    """
    
    MODEL = "gpt-5-mini"
    
    GENERATE_QUESTIONS_PROMPT = """You are a smart shopping assistant. When a user wants to search for a product, 
you need to ask 3 clarification questions to better understand their needs.

RULES:
1. Generate exactly 3 questions relevant to the product type
2. Each question should have 4-6 options
3. The last option should always be "Any" or "No preference"
4. Questions should cover different aspects like: brand, use case, budget, features, size, etc.
5. Adapt questions to the product category (laptop questions differ from skincare questions)
6. Keep questions concise and clear

EXAMPLES:
- For "laptop": Ask about brand preference, primary use (gaming/work/study), budget range
- For "TV": Ask about screen size, smart features, brand preference
- For "headphones": Ask about type (over-ear/in-ear), use case (music/gaming/calls), wireless preference
"""
    
    BUILD_QUERY_PROMPT = """Based on the user's original keyword and their answers to clarification questions,
build an optimized search query for BestBuy.

RULES:
1. Query should be in English
2. Keep it concise - only include relevant keywords
3. If user answered "Any" or "No preference", skip that criterion
4. Include price constraint if user specified a budget (e.g., "under $800")
5. Focus on searchable terms that BestBuy would understand
"""
    
    def __init__(self):
        """Initialize with OpenAI client."""
        self.openai = OpenAI()
        logging.info("ClarificationAgent initialized with GPT-5-mini")
    
    def generate_questions(self, keyword: str) -> ClarificationResponse:
        """
        Generate 3 clarification questions based on user's keyword.
        
        Args:
            keyword: User's initial search keyword (e.g., "laptop")
            
        Returns:
            ClarificationResponse with 3 questions and options
        """
        logging.info(f"🤖 Generating clarification questions for: '{keyword}'")
        
        result = self.openai.chat.completions.parse(
            model=self.MODEL,
            messages=[
                {"role": "system", "content": self.GENERATE_QUESTIONS_PROMPT},
                {"role": "user", "content": f"Product keyword: {keyword}"}
            ],
            response_format=ClarificationResponse
        )
        
        response = result.choices[0].message.parsed
        logging.info(f"✅ Generated {len(response.questions)} questions")
        return response
    
    def build_refined_query(
        self, 
        keyword: str, 
        questions: List[ClarificationQuestion],
        answers: List[str]
    ) -> RefinedQuery:
        """
        Build refined search query from user's answers.
        
        Args:
            keyword: Original keyword
            questions: List of questions that were asked
            answers: User's answers to each question
            
        Returns:
            RefinedQuery with optimized search string
        """
        logging.info(f"🔧 Building refined query...")
        
        # Format Q&A for the prompt
        qa_text = ""
        for i, (q, a) in enumerate(zip(questions, answers), 1):
            qa_text += f"Q{i}: {q.question}\nA{i}: {a}\n\n"
        
        user_message = f"""Original keyword: {keyword}

User's answers:
{qa_text}

Build an optimized search query based on these answers."""
        
        result = self.openai.chat.completions.parse(
            model=self.MODEL,
            messages=[
                {"role": "system", "content": self.BUILD_QUERY_PROMPT},
                {"role": "user", "content": user_message}
            ],
            response_format=RefinedQuery
        )
        
        refined = result.choices[0].message.parsed
        logging.info(f"✅ Refined query: '{refined.query}'")
        return refined


# ============================================================================
# SECTION 4: GLOBAL VARIABLES
# ============================================================================

ensemble = None
messenger = None
clarification_agent = None
current_opportunities = []
log_queue = None

# Store current clarification state
current_questions: Optional[ClarificationResponse] = None
current_keyword: str = ""
current_max_urls: int = 10  # Default max URLs


# ============================================================================
# SECTION 5: AGENT INITIALIZATION
# ============================================================================

def init_agents():
    """
    Initialize ChromaDB, EnsembleAgent, MessagingAgent, and ClarificationAgent.
    This is called once at startup.
    """
    global ensemble, messenger, clarification_agent
    
    if ensemble is None:
        print("Initializing ChromaDB...")
        client = chromadb.PersistentClient(path=DB_PATH)
        collection = client.get_or_create_collection('products')
        print(f"ChromaDB collection: {collection.name}")
        print(f"Number of documents: {collection.count()}")
        
        print("\nInitializing EnsembleAgent...")
        ensemble = EnsembleAgent(collection)
        print("✅ EnsembleAgent ready!")
        
        print("\nInitializing MessagingAgent...")
        messenger = MessagingAgent()
        print("✅ MessagingAgent ready!")
        
        print("\nInitializing ClarificationAgent...")
        clarification_agent = ClarificationAgent()
        print("✅ ClarificationAgent ready!")
        
        print("\n🎉 All agents initialized successfully!\n")


# ============================================================================
# SECTION 6: PIPELINE FUNCTIONS
# ============================================================================

def search_bestbuy(keyword: str, max_urls: int = 10) -> List[str]:
    """
    Step 1: Search for BestBuy product URLs using Brave Search.
    
    Args:
        keyword: Search keyword (e.g., "Smart TV")
        max_urls: Maximum number of URLs to return
    
    Returns:
        List of BestBuy product URLs
    """
    search_agent = BestBuySearchAgent()
    urls = search_agent.search(keyword, max_urls=max_urls)
    return urls


def filter_sales(urls: List[str]) -> List[str]:
    """
    Step 2: Filter URLs to keep only products on sale.
    
    Args:
        urls: List of product URLs
    
    Returns:
        List of URLs for products currently on sale
    """
    return filter_sale_urls(urls)


async def scrape_products(urls: List[str]) -> List[ScrapedBestBuyDeal]:
    """
    Step 3: Scrape product details using Playwright.
    
    Args:
        urls: List of sale product URLs
    
    Returns:
        List of scraped product data
    """
    return await scrape_bestbuy_products(urls, headless=False)


def select_top_deals(scraped_deals: List[ScrapedBestBuyDeal]) -> DealSelection:
    """
    Step 4: Select top 5 deals using GPT-5-mini.
    
    Args:
        scraped_deals: List of scraped products
    
    Returns:
        DealSelection with top 5 deals
    """
    scanner = BestBuyScannerAgent()
    return scanner.scan(scraped_deals)


def estimate_prices(deal_selection: DealSelection, ensemble_agent: EnsembleAgent) -> List[Opportunity]:
    """
    Step 5: Estimate prices and calculate discounts.
    
    Args:
        deal_selection: Top deals selected
        ensemble_agent: Initialized EnsembleAgent
    
    Returns:
        List of opportunities sorted by discount (descending)
    """
    opportunities = []
    
    for deal in deal_selection.deals:
        estimate = ensemble_agent.price(deal.product_description)
        discount = estimate - deal.price
        opportunity = Opportunity(
            deal=deal,
            estimate=estimate,
            discount=discount
        )
        opportunities.append(opportunity)
    
    # Sort by discount descending
    opportunities.sort(key=lambda x: x.discount, reverse=True)
    return opportunities


# ============================================================================
# SECTION 7: GRADIO HELPERS
# ============================================================================

class QueueHandler(logging.Handler):
    """Custom logging handler that puts logs into a queue for Gradio."""
    
    def __init__(self, log_queue):
        super().__init__()
        self.log_queue = log_queue

    def emit(self, record):
        self.log_queue.put(self.format(record))


def setup_logging(q):
    """Setup logging to capture all logs into queue."""
    global log_queue
    log_queue = q
    
    handler = QueueHandler(q)
    formatter = logging.Formatter(
        "[%(asctime)s] %(message)s",
        datefmt="%H:%M:%S",
    )
    handler.setFormatter(formatter)
    
    # Add handler to root logger
    logger = logging.getLogger()
    # Remove existing QueueHandlers to avoid duplicates
    for h in logger.handlers[:]:
        if isinstance(h, QueueHandler):
            logger.removeHandler(h)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


def html_for_logs(log_data: List[str]) -> str:
    """Convert log data to HTML for display."""
    # Keep last 20 logs
    recent_logs = log_data[-20:]
    # Format each log with color
    formatted = [reformat(log) for log in recent_logs]
    output = '<br>'.join(formatted)
    return f"""
    <div style="height: 350px; overflow-y: auto; border: 1px solid #444; 
                background-color: #1a1a2e; padding: 10px; font-family: monospace; 
                font-size: 12px; border-radius: 8px;">
    {output}
    </div>
    """


def opportunities_to_table(opportunities: List[Opportunity]) -> list:
    """
    Convert opportunities to data for Gradio Dataframe.
    
    Returns:
        List of rows: [Product, Sale $, Estimate $, Discount $, Discount %, URL]
    """
    rows = []
    for opp in opportunities:
        discount_pct = (opp.discount / opp.estimate * 100) if opp.estimate > 0 else 0
        status = "🔥" if opp.discount > 200 else ("✅" if opp.discount > 100 else ("👍" if opp.discount > 0 else "❌"))
        rows.append([
            opp.deal.product_description[:60] + "...",
            f"${opp.deal.price:.2f}",
            f"${opp.estimate:.2f}",
            f"${opp.discount:.2f}",
            f"{discount_pct:.1f}% {status}",
            opp.deal.url
        ])
    return rows


def format_questions_html(questions: List[ClarificationQuestion]) -> str:
    """Format clarification questions as HTML for display."""
    html = ""
    for i, q in enumerate(questions, 1):
        options_html = ", ".join(q.options)
        html += f"""
        <div style="margin-bottom: 15px; padding: 10px; background: #2a2a4a; border-radius: 8px;">
            <strong style="color: #87CEEB;">Q{i}: {q.question}</strong>
            <br><span style="color: #888; font-size: 0.9em;">Options: {options_html}</span>
        </div>
        """
    return f"""
    <div style="background: #1a1a2e; padding: 15px; border-radius: 10px; border: 1px solid #444;">
        <h4 style="color: #87CEEB; margin-top: 0;">🤖 Clarification Questions</h4>
        {html}
        <p style="color: #888; font-size: 0.85em;">
            💡 Answer these questions below, or click "Skip" to search directly.
        </p>
    </div>
    """


# ============================================================================
# SECTION 8: CLARIFICATION FLOW FUNCTIONS
# ============================================================================

def generate_questions_handler(keyword: str):
    """
    Handle keyword input and generate clarification questions.
    
    Args:
        keyword: User's initial keyword
    
    Returns:
        Tuple[str, str, bool, bool]: (questions_html, status, show_answers, show_skip)
    """
    global current_questions, current_keyword
    
    if not keyword or len(keyword.strip()) < 2:
        return (
            "",
            "❌ Please enter a keyword (at least 2 characters)",
            gr.update(visible=False),  # answers section
            gr.update(visible=False),  # skip button
        )
    
    try:
        current_keyword = keyword.strip()
        logging.info(f"Generating questions for: {current_keyword}")
        
        response = clarification_agent.generate_questions(current_keyword)
        current_questions = response
        
        questions_html = format_questions_html(response.questions)
        
        return (
            questions_html,
            f"✅ Category: {response.product_category} | Answer the questions below or skip to search directly.",
            gr.update(visible=True),   # Show answers section
            gr.update(visible=True),   # Show skip button
        )
        
    except Exception as e:
        logging.error(f"Error generating questions: {e}")
        return (
            "",
            f"❌ Error: {str(e)}",
            gr.update(visible=False),
            gr.update(visible=False),
        )


def submit_answers_handler(answer1: str, answer2: str, answer3: str, max_urls: int, initial_log_data: List[str]):
    """
    Handle submit answers and run clarification flow.
    
    Yields updates during pipeline execution.
    """
    global current_questions, current_keyword, current_max_urls
    
    if not current_questions:
        yield [], "❌ Please generate questions first!", "", html_for_logs(["❌ Please generate questions first!"])
        return
    
    current_max_urls = int(max_urls) if max_urls else 10
    answers = [answer1.strip(), answer2.strip(), answer3.strip()]
    
    # Build refined query
    try:
        refined = clarification_agent.build_refined_query(
            current_keyword,
            current_questions.questions,
            answers
        )
        search_query = refined.query
        comparison_text = f"🔄 Original: \"{current_keyword}\" → Refined: \"{search_query}\""
    except Exception as e:
        logging.error(f"Error building refined query: {e}")
        search_query = current_keyword
        comparison_text = f"⚠️ Using original keyword: \"{current_keyword}\""
    
    # Now run the pipeline with refined query
    yield from run_search_pipeline(search_query, comparison_text, initial_log_data)


def skip_and_search_handler(max_urls: int, initial_log_data: List[str]):
    """
    Handle skip button - search with original keyword.
    
    Yields updates during pipeline execution.
    """
    global current_keyword, current_max_urls
    
    if not current_keyword:
        yield [], "❌ Please enter a keyword first!", "", html_for_logs(["❌ Please enter a keyword first!"])
        return
    
    current_max_urls = int(max_urls) if max_urls else 10
    comparison_text = f"⏩ Skip mode - searching with: \"{current_keyword}\""
    
    yield from run_search_pipeline(current_keyword, comparison_text, initial_log_data)


# ============================================================================
# SECTION 9: MAIN SEARCH PIPELINE
# ============================================================================

def do_search_pipeline(search_query: str, max_urls: int, result_queue: queue.Queue):
    """
    Worker function that runs in a separate thread.
    Executes the full search pipeline and puts result in queue.
    
    Args:
        search_query: Search query (refined or original)
        max_urls: Maximum URLs to search
        result_queue: Queue to put final result
    """
    global current_opportunities
    
    try:
        # Step 1: Search
        logging.info(f"🔍 [Step 1/5] Searching for '{search_query}' on BestBuy...")
        urls = search_bestbuy(search_query, max_urls)
        if not urls:
            result_queue.put(([], "❌ No products found. Try a different keyword."))
            return
        logging.info(f"✅ Found {len(urls)} product URLs")
        
        # Step 2: Filter sales
        logging.info(f"🏷️ [Step 2/5] Filtering sale items from {len(urls)} URLs...")
        sale_urls = filter_sales(urls)
        if not sale_urls:
            result_queue.put(([], "❌ No sale items found. Try a different keyword."))
            return
        logging.info(f"✅ Found {len(sale_urls)} products on SALE")
        
        # Step 3: Scrape (async)
        logging.info(f"📦 [Step 3/5] Scraping {len(sale_urls)} products with Playwright...")
        
        # Handle async in sync context
        try:
            loop = asyncio.get_event_loop()
        except RuntimeError:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
        
        scraped = loop.run_until_complete(scrape_products(sale_urls))
        if not scraped:
            result_queue.put(([], "❌ Could not scrape product details."))
            return
        logging.info(f"✅ Scraped {len(scraped)} products successfully")
        
        # Step 4: Select top deals
        logging.info(f"🤖 [Step 4/5] Selecting top 5 deals with GPT-5-mini...")
        deal_selection = select_top_deals(scraped)
        if not deal_selection or not deal_selection.deals:
            result_queue.put(([], "❌ Could not select deals."))
            return
        logging.info(f"✅ Selected {len(deal_selection.deals)} best deals")
        
        # Step 5: Estimate prices
        logging.info(f"💰 [Step 5/5] Estimating prices with EnsembleAgent (3 models)...")
        opportunities = estimate_prices(deal_selection, ensemble)
        current_opportunities = opportunities  # Save for push notification
        logging.info(f"✅ Estimated {len(opportunities)} opportunities")
        
        if opportunities:
            best = opportunities[0]
            logging.info(f"🏆 BEST DEAL: ${best.deal.price:.2f} → Est: ${best.estimate:.2f} = Discount ${best.discount:.2f}")
        
        # Return results
        table = opportunities_to_table(opportunities)
        status = f"✅ Found {len(opportunities)} deals! Best discount: ${opportunities[0].discount:.2f}" if opportunities else "No deals found."
        
        result_queue.put((table, status))
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        result_queue.put(([], f"❌ Error: {str(e)}"))


def run_search_pipeline(search_query: str, comparison_text: str, initial_log_data: List[str]):
    """
    Generator function for Gradio that yields updates during pipeline execution.
    
    Args:
        search_query: The query to search (refined or original)
        comparison_text: Text showing original vs refined query
        initial_log_data: Previous log data
    
    Yields:
        Tuple of (table_data, status_text, comparison_html, logs_html)
    """
    global current_max_urls
    max_urls = current_max_urls if current_max_urls else 10
    
    # Setup
    log_q = queue.Queue()
    result_q = queue.Queue()
    setup_logging(log_q)
    
    log_data = initial_log_data.copy() if initial_log_data else []
    log_data.append(f"🚀 Starting search: {search_query} (max {max_urls} URLs)")
    
    # Start worker thread
    thread = threading.Thread(
        target=do_search_pipeline,
        args=(search_query, max_urls, result_q)
    )
    thread.start()
    
    # Yield updates while thread is running
    final_result = None
    while thread.is_alive() or not log_q.empty() or final_result is None:
        # Check for new logs
        try:
            while True:
                message = log_q.get_nowait()
                log_data.append(message)
        except queue.Empty:
            pass
        
        # Check for result
        try:
            final_result = result_q.get_nowait()
        except queue.Empty:
            pass
        
        # Yield current state (with HTML logs)
        if final_result:
            table, status = final_result
            yield table, status, comparison_text, html_for_logs(log_data)
        else:
            yield [], "⏳ Processing...", comparison_text, html_for_logs(log_data)
        
        time.sleep(0.1)
    
    # Final yield
    if final_result:
        table, status = final_result
        log_data.append(f"✅ Pipeline completed!")
        yield table, status, comparison_text, html_for_logs(log_data)


# ============================================================================
# SECTION 10: PUSH NOTIFICATION
# ============================================================================

def send_push_notification(selected_index: int) -> str:
    """
    Send push notification for selected deal.
    
    Args:
        selected_index: Index of deal in table (0-based)
    
    Returns:
        Status message
    """
    global current_opportunities
    
    if not current_opportunities:
        return "❌ No deals available. Search first!"
    
    idx = int(selected_index)
    if idx < 0 or idx >= len(current_opportunities):
        return f"❌ Invalid selection. Choose 0-{len(current_opportunities)-1}"
    
    opp = current_opportunities[idx]
    
    try:
        messenger.notify(
            description=opp.deal.product_description[:200],
            deal_price=opp.deal.price,
            estimated_true_value=opp.estimate,
            url=opp.deal.url
        )
        return f"✅ Sent! Deal #{idx}: {opp.deal.product_description[:40]}... (${opp.deal.price:.2f})"
    except Exception as e:
        return f"❌ Failed: {str(e)}"


# ============================================================================
# SECTION 11: GRADIO UI DEFINITION
# ============================================================================

def create_gradio_app():
    """Create and return Gradio app with clarification flow."""
    
    with gr.Blocks(
        title="BestBuy Deal Finder v2",
        theme=gr.themes.Soft(),
        fill_width=True,
    ) as app:
        
        # State for logs
        log_data_state = gr.State([])
        
        # Header
        gr.Markdown("""
        # 🔍 BestBuy Deal Finder v2 - With Clarification
                
        **New Flow:** 
        1️⃣ Enter Keyword → 2️⃣ Answer Questions (or Skip) → 3️⃣ AI Search → 4️⃣ Estimate Prices
        """)
        
        # ==================== STEP 1: KEYWORD INPUT ====================
        with gr.Group():
            gr.Markdown("### 📝 Step 1: Enter Product Keyword")
            with gr.Row():
                keyword_input = gr.Textbox(
                    label="🔎 What are you looking for?",
                    placeholder="Enter product keyword (e.g., laptop, Smart TV, headphones)",
                    scale=3
                )
                max_urls_input = gr.Number(
                    label="Max URLs",
                    value=10,
                    minimum=5,
                    maximum=30,
                    precision=0,
                    scale=1
                )
                generate_btn = gr.Button("🤖 Generate Questions", variant="primary", scale=1)
        
        # Status message
        status_text = gr.Textbox(
            label="Status",
            interactive=False,
            value="Enter a keyword and click 'Generate Questions'"
        )
        
        # ==================== STEP 2: CLARIFICATION QUESTIONS ====================
        with gr.Group() as questions_section:
            questions_html = gr.HTML(
                value='<div style="padding: 20px; text-align: center; color: #888;">Questions will appear here after you enter a keyword...</div>'
            )
        
        # ==================== STEP 3: ANSWERS INPUT ====================
        with gr.Group(visible=False) as answers_section:
            gr.Markdown("### ✍️ Step 2: Answer the Questions")
            gr.Markdown("*Type your answers freely (e.g., 'Acer', 'for students', 'under $800') or use options above*")
            
            with gr.Row():
                answer1 = gr.Textbox(label="Answer 1", placeholder="Your answer to Q1...")
                answer2 = gr.Textbox(label="Answer 2", placeholder="Your answer to Q2...")
                answer3 = gr.Textbox(label="Answer 3", placeholder="Your answer to Q3...")
            
            with gr.Row():
                submit_btn = gr.Button("✅ Submit & Search", variant="primary", scale=2)
                skip_btn = gr.Button("⏩ Skip, Search Now", variant="secondary", scale=1)
        
        # Comparison text (Original vs Refined query)
        comparison_text = gr.Textbox(
            label="🔄 Query Comparison",
            interactive=False,
            visible=True,
            value=""
        )
        
        # ==================== RESULTS SECTION ====================
        gr.Markdown("### 🏆 Results")
        
        with gr.Row():
            # Left: Results Table
            with gr.Column(scale=3):
                results_table = gr.Dataframe(
                    headers=["Product", "Sale $", "Estimate $", "Discount $", "Discount %", "URL"],
                    label="Deal Results (sorted by discount)",
                    wrap=True,
                    column_widths=[4, 1, 1, 1, 1, 2],
                    max_height=350,
                )
            
            # Right: Real-time Logs
            with gr.Column(scale=2):
                gr.Markdown("### 📋 Pipeline Logs")
                logs_html = gr.HTML(
                    value='<div style="height: 350px; background-color: #1a1a2e; border-radius: 8px; padding: 10px; font-family: monospace; color: #87CEEB;">Ready to search...</div>'
                )
        
        # ==================== PUSH NOTIFICATION ====================
        with gr.Row():
            deal_index = gr.Number(
                label="Deal # to notify (0 = best deal)",
                value=0,
                minimum=0,
                precision=0,
                scale=1
            )
            push_btn = gr.Button("📱 Send Push Notification", variant="secondary", scale=1)
        
        push_status = gr.Textbox(
            label="📱 Notification Status",
            interactive=False,
            placeholder="Click 'Send Push Notification' to send...",
            lines=2,
        )
        
        # ==================== EVENT HANDLERS ====================
        
        # Step 1: Generate questions
        generate_btn.click(
            fn=generate_questions_handler,
            inputs=[keyword_input],
            outputs=[questions_html, status_text, answers_section, skip_btn]
        )
        
        # Step 2a: Submit answers (clarification flow)
        submit_btn.click(
            fn=submit_answers_handler,
            inputs=[answer1, answer2, answer3, max_urls_input, log_data_state],
            outputs=[results_table, status_text, comparison_text, logs_html]
        )
        
        # Step 2b: Skip and search (skip flow)
        skip_btn.click(
            fn=skip_and_search_handler,
            inputs=[max_urls_input, log_data_state],
            outputs=[results_table, status_text, comparison_text, logs_html]
        )
        
        # Push notification
        push_btn.click(
            fn=send_push_notification,
            inputs=[deal_index],
            outputs=[push_status],
        )
        
        # Footer
        gr.Markdown("""
        ---
        **Legend:** 🔥 Discount > $200 | ✅ Discount > $100 | 👍 Positive discount | ❌ Overpriced
        
        **Tips:** 
        - Use clarification for better results (68% discount vs 27% in tests!)
        - Skip is faster but may miss targeted deals
        - Browser window will open during Playwright scraping
        """)
    
    return app


# ============================================================================
# SECTION 12: MAIN ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("🚀 BestBuy Deal Finder v2 - With Clarification Flow")
    print("=" * 60)
    
    # Initialize agents (this may take 5-10 seconds)
    init_agents()
    
    # Create and launch Gradio app
    app = create_gradio_app()
    
    print("\n" + "=" * 60)
    print("✅ Ready! Opening browser...")
    print("=" * 60 + "\n")
    
    app.launch(share=False, inbrowser=True)
