"""
Multi-Source Deal Finder - Gradio Web App (bestbuy3.py)

Search on BOTH BestBuy AND Amazon simultaneously.
Enhanced version with chatbot-style clarification questions before search.

Supports 2 flows:
1. Clarification Flow: User answers 3 questions → Refined query → Better deals
2. Skip Flow: User skips questions → Search with original keyword

Workflow:
1. [ClarificationAgent] Generate clarification questions (GPT-5-mini)
2. [ClarificationAgent] Build refined query from answers OR skip
3. [PARALLEL] Search URLs on BestBuy + Amazon (Brave MCP)
4. [Filter] BestBuy: BeautifulSoup | Amazon: Playwright
5. [Scrape] Both: Playwright
6. [GPT] Select top 5 deals from COMBINED pool
7. [EnsembleAgent] Estimate prices (3 models)
"""

import os
import sys
import logging
import queue
import threading
import time
import asyncio
from typing import List, Optional, Tuple, Union
from concurrent.futures import ThreadPoolExecutor, as_completed

import gradio as gr
import chromadb
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from openai import OpenAI

# Import BestBuy modules
from price_agents.bestbuy_deals import (
    ScrapedBestBuyDeal,
    filter_sale_urls,
    scrape_bestbuy_products
)
from price_agents.bestbuy_scanner_agent import BestBuySearchAgent

# Import Amazon modules
from price_agents.amazon_deals import (
    ScrapedAmazonDeal,
    filter_amazon_sale_urls_playwright,
    scrape_amazon_products
)
from price_agents.amazon_scanner_agent import AmazonSearchAgent

# Import existing agents
from price_agents.agent import Agent as BaseAgent
from price_agents.ensemble_agent import EnsembleAgent
from price_agents.messaging_agent import MessagingAgent
from price_agents.deals import Deal, DealSelection, Opportunity
from log_utils import reformat


# ============================================================================
# SECTION 1: SETUP & CONFIGURATION
# ============================================================================

# Load environment variables
load_dotenv(override=True)

# Setup logging
logging.basicConfig(level=logging.INFO)
root = logging.getLogger()
root.setLevel(logging.INFO)

# Database path
DB_PATH = "products_vectorstore"


# ============================================================================
# SECTION 2: PYDANTIC SCHEMAS FOR CLARIFICATION
# ============================================================================

class ClarificationQuestion(BaseModel):
    """A single clarification question with options."""
    question: str = Field(description="The clarification question in English")
    options: List[str] = Field(
        description="4-6 options for the user to choose from. Last option should always be 'Any' or 'No preference'",
        min_length=3,
        max_length=6
    )


class ClarificationResponse(BaseModel):
    """Response containing clarification questions generated by LLM."""
    product_category: str = Field(description="Detected product category (e.g., 'laptop', 'TV', 'headphones')")
    questions: List[ClarificationQuestion] = Field(
        description="Exactly 3 clarification questions to help refine the search",
        min_length=3,
        max_length=3
    )


class RefinedQuery(BaseModel):
    """Refined search query built from user answers."""
    query: str = Field(description="Optimized search query in English for product search")
    summary: str = Field(description="Brief summary of what the user is looking for")


# ============================================================================
# SECTION 3: UNIFIED SCRAPED DEAL (for combining sources)
# ============================================================================

class UnifiedScrapedDeal:
    """
    A unified representation of a scraped deal from any source (BestBuy or Amazon).
    
    This allows combining deals from different sources into a single pool
    for GPT to select the best ones.
    
    Attributes:
        title: Product title (max 200 chars)
        brand: Product brand (optional)
        price: Sale price in USD
        features: Product features text (max 1500 chars)
        url: Product URL
        source: 'BestBuy' or 'Amazon'
    """
    
    def __init__(
        self,
        title: str,
        brand: Optional[str],
        price: float,
        features: str,
        url: str,
        source: str
    ):
        """
        Initialize unified deal.
        
        Args:
            title: Product title
            brand: Product brand (optional)
            price: Sale price in USD
            features: Product features/description text
            url: Product URL
            source: 'BestBuy' or 'Amazon'
        """
        self.title = title[:200] if title else "Unknown"
        self.brand = brand.strip() if brand else None
        self.price = price
        self.features = features[:1500] if features else ""
        self.url = url
        self.source = source
    
    def __repr__(self) -> str:
        """Return a short string description."""
        return f"<[{self.source}] {self.title[:40]}... | ${self.price}>"
    
    def describe(self) -> str:
        """
        Return a longer string to describe this deal for use in calling a model.
        
        Returns:
            Formatted string with Source, Title, Brand, Price, Features, URL
        """
        parts = [f"Source: {self.source}", f"Title: {self.title}"]
        
        if self.brand:
            parts.append(f"Brand: {self.brand}")
        
        parts.append(f"Price: ${self.price:.2f}")
        
        if self.features and len(self.features) > 10:
            parts.append(f"Features: {self.features.strip()}")
        
        parts.append(f"URL: {self.url}")
        
        return "\n".join(parts)
    
    @classmethod
    def from_bestbuy(cls, deal: ScrapedBestBuyDeal) -> "UnifiedScrapedDeal":
        """Convert ScrapedBestBuyDeal to UnifiedScrapedDeal."""
        return cls(
            title=deal.title,
            brand=deal.brand,
            price=deal.price,
            features=deal.features,
            url=deal.url,
            source="BestBuy"
        )
    
    @classmethod
    def from_amazon(cls, deal: ScrapedAmazonDeal) -> "UnifiedScrapedDeal":
        """Convert ScrapedAmazonDeal to UnifiedScrapedDeal."""
        return cls(
            title=deal.title,
            brand=deal.brand,
            price=deal.price,
            features=deal.features,
            url=deal.url,
            source="Amazon"
        )


# ============================================================================
# SECTION 4: CLARIFICATION AGENT (Reused from bestbuy2.py)
# ============================================================================

class ClarificationAgent:
    """
    Agent that generates clarification questions before search.
    
    Uses GPT-5-mini to:
    1. Generate 3 relevant questions based on user's keyword
    2. Build a refined search query from user's answers
    """
    
    MODEL = "gpt-5-mini"
    
    GENERATE_QUESTIONS_PROMPT = """You are a smart shopping assistant. When a user wants to search for a product, 
you need to ask 3 clarification questions to better understand their needs.

RULES:
1. Generate exactly 3 questions relevant to the product type
2. Each question should have 4-6 options
3. The last option should always be "Any" or "No preference"
4. Questions should cover different aspects like: brand, use case, budget, features, size, etc.
5. Adapt questions to the product category (laptop questions differ from skincare questions)
6. Keep questions concise and clear

EXAMPLES:
- For "laptop": Ask about brand preference, primary use (gaming/work/study), budget range
- For "TV": Ask about screen size, smart features, brand preference
- For "headphones": Ask about type (over-ear/in-ear), use case (music/gaming/calls), wireless preference
"""
    
    BUILD_QUERY_PROMPT = """Based on the user's original keyword and their answers to clarification questions,
build an optimized search query for product search on e-commerce sites.

RULES:
1. Query should be in English
2. Keep it concise - only include relevant keywords
3. If user answered "Any" or "No preference", skip that criterion
4. Include price constraint if user specified a budget (e.g., "under $800")
5. Focus on searchable terms that e-commerce sites would understand
"""
    
    def __init__(self):
        """Initialize with OpenAI client."""
        self.openai = OpenAI()
        logging.info("ClarificationAgent initialized with GPT-5-mini")
    
    def generate_questions(self, keyword: str) -> ClarificationResponse:
        """
        Generate 3 clarification questions based on user's keyword.
        
        Args:
            keyword: User's initial search keyword (e.g., "laptop")
            
        Returns:
            ClarificationResponse with 3 questions and options
        """
        logging.info(f"Generating clarification questions for: '{keyword}'")
        
        result = self.openai.chat.completions.parse(
            model=self.MODEL,
            messages=[
                {"role": "system", "content": self.GENERATE_QUESTIONS_PROMPT},
                {"role": "user", "content": f"Product keyword: {keyword}"}
            ],
            response_format=ClarificationResponse
        )
        
        response = result.choices[0].message.parsed
        logging.info(f"Generated {len(response.questions)} questions")
        return response
    
    def build_refined_query(
        self, 
        keyword: str, 
        questions: List[ClarificationQuestion],
        answers: List[str]
    ) -> RefinedQuery:
        """
        Build refined search query from user's answers.
        
        Args:
            keyword: Original keyword
            questions: List of questions that were asked
            answers: User's answers to each question
            
        Returns:
            RefinedQuery with optimized search string
        """
        logging.info(f"Building refined query...")
        
        # Format Q&A for the prompt
        qa_text = ""
        for i, (q, a) in enumerate(zip(questions, answers), 1):
            qa_text += f"Q{i}: {q.question}\nA{i}: {a}\n\n"
        
        user_message = f"""Original keyword: {keyword}

User's answers:
{qa_text}

Build an optimized search query based on these answers."""
        
        result = self.openai.chat.completions.parse(
            model=self.MODEL,
            messages=[
                {"role": "system", "content": self.BUILD_QUERY_PROMPT},
                {"role": "user", "content": user_message}
            ],
            response_format=RefinedQuery
        )
        
        refined = result.choices[0].message.parsed
        logging.info(f"Refined query: '{refined.query}'")
        return refined


# ============================================================================
# SECTION 5: MULTI-SOURCE SCANNER AGENT
# ============================================================================

class MultiSourceScannerAgent(BaseAgent):
    """
    Agent that uses GPT-5-mini to select the best 5 deals from BOTH BestBuy and Amazon.
    
    This agent:
    1. Takes a list of UnifiedScrapedDeal objects (from both sources)
    2. Uses GPT-5-mini with structured outputs
    3. Returns a DealSelection with the best 5 deals (may include both sources)
    """
    
    name = "Multi-Source Scanner Agent"
    color = BaseAgent.CYAN
    MODEL = "gpt-5-mini"
    
    SYSTEM_PROMPT = """You identify and summarize the 5 most detailed deals from a combined list of products from BestBuy and Amazon.
Select deals that have the most detailed, high quality description and the most clear price.
You can select from EITHER source (BestBuy or Amazon) - pick the best overall deals.

Respond strictly in JSON with no explanation. You should provide the price as a number derived from the description.
Most important is that you respond with the 5 deals that have the most detailed product description with price.

**IMPORTANT:**
1. Focus on the product features and specifications, not sales terms.
2. The product_description should be a 3-4 sentence summary of the product itself.
3. Include the SOURCE (BestBuy or Amazon) at the beginning of product_description.
4. Price must be greater than 0.
5. Keep the original URL exactly as provided.
"""
    
    USER_PROMPT_PREFIX = """Respond with the most promising 5 deals from this COMBINED list (BestBuy + Amazon).
Select those which have the most detailed, high quality product description and a clear price that is greater than 0.
You can pick from EITHER source - just choose the 5 best overall deals.

You should rephrase the description to be a summary of the product itself, not the terms of the deal.
START the product_description with "[BestBuy]" or "[Amazon]" to indicate the source.

Deals:

"""
    
    USER_PROMPT_SUFFIX = "\n\nInclude up to 5 deals, no more. Pick the best from EITHER source."
    
    def __init__(self):
        """Initialize with OpenAI client."""
        self.log("Multi-Source Scanner Agent is initializing")
        self.openai = OpenAI()
        self.log("Multi-Source Scanner Agent is ready")
    
    def make_user_prompt(self, unified_deals: List[UnifiedScrapedDeal]) -> str:
        """
        Create user prompt from unified deals.
        
        Args:
            unified_deals: List of UnifiedScrapedDeal objects from both sources
            
        Returns:
            Formatted prompt string for GPT
        """
        user_prompt = self.USER_PROMPT_PREFIX
        user_prompt += "\n\n".join([deal.describe() for deal in unified_deals])
        user_prompt += self.USER_PROMPT_SUFFIX
        return user_prompt
    
    def scan(self, unified_deals: List[UnifiedScrapedDeal]) -> Optional[DealSelection]:
        """
        Call GPT-5-mini to select the best 5 deals from combined BestBuy + Amazon pool.
        
        Uses OpenAI structured outputs to ensure response conforms to DealSelection schema.
        
        Args:
            unified_deals: List of UnifiedScrapedDeal from both sources
            
        Returns:
            DealSelection with up to 5 best deals, or None if no valid deals
        """
        if not unified_deals:
            self.log("No deals to scan")
            return None
        
        # Filter deals with price > 0
        valid_deals = [d for d in unified_deals if d.price > 0]
        if not valid_deals:
            self.log("No deals with valid price > 0")
            return None
        
        user_prompt = self.make_user_prompt(valid_deals)
        
        self.log(f"Calling {self.MODEL} with {len(valid_deals)} deals (BestBuy + Amazon)...")
        
        result = self.openai.chat.completions.parse(
            model=self.MODEL,
            messages=[
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            response_format=DealSelection,
        )
        
        selection = result.choices[0].message.parsed
        
        # Filter out any deals with price <= 0
        selection.deals = [deal for deal in selection.deals if deal.price > 0]
        
        self.log(f"Selected {len(selection.deals)} deals from combined pool")
        
        return selection


# ============================================================================
# SECTION 6: GLOBAL VARIABLES
# ============================================================================

ensemble = None
messenger = None
clarification_agent = None
multi_scanner = None
current_opportunities = []
log_queue = None

# Store current clarification state
current_questions: Optional[ClarificationResponse] = None
current_keyword: str = ""
current_max_urls: int = 10


# ============================================================================
# SECTION 7: AGENT INITIALIZATION
# ============================================================================

def init_agents():
    """
    Initialize ChromaDB, EnsembleAgent, MessagingAgent, ClarificationAgent, and MultiSourceScanner.
    This is called once at startup.
    """
    global ensemble, messenger, clarification_agent, multi_scanner
    
    if ensemble is None:
        print("Initializing ChromaDB...")
        client = chromadb.PersistentClient(path=DB_PATH)
        collection = client.get_or_create_collection('products')
        print(f"ChromaDB collection: {collection.name}")
        print(f"Number of documents: {collection.count()}")
        
        print("\nInitializing EnsembleAgent...")
        ensemble = EnsembleAgent(collection)
        print("EnsembleAgent ready!")
        
        print("\nInitializing MessagingAgent...")
        messenger = MessagingAgent()
        print("MessagingAgent ready!")
        
        print("\nInitializing ClarificationAgent...")
        clarification_agent = ClarificationAgent()
        print("ClarificationAgent ready!")
        
        print("\nInitializing MultiSourceScannerAgent...")
        multi_scanner = MultiSourceScannerAgent()
        print("MultiSourceScannerAgent ready!")
        
        print("\nAll agents initialized successfully!\n")


# ============================================================================
# SECTION 8: PIPELINE FUNCTIONS
# ============================================================================

def search_bestbuy(keyword: str, max_urls: int = 10) -> List[str]:
    """
    Search for BestBuy product URLs using Brave Search.
    
    Args:
        keyword: Search keyword (e.g., "Smart TV")
        max_urls: Maximum number of URLs to return
    
    Returns:
        List of BestBuy product URLs
    """
    try:
        search_agent = BestBuySearchAgent()
        urls = search_agent.search(keyword, max_urls=max_urls)
        return urls
    except Exception as e:
        logging.error(f"BestBuy search error: {e}")
        return []


def search_amazon(keyword: str, max_urls: int = 10) -> List[str]:
    """
    Search for Amazon product URLs using Brave Search.
    
    Args:
        keyword: Search keyword (e.g., "Smart TV")
        max_urls: Maximum number of URLs to return
    
    Returns:
        List of Amazon product URLs
    """
    try:
        search_agent = AmazonSearchAgent()
        urls = search_agent.search(keyword, max_urls=max_urls)
        return urls
    except Exception as e:
        logging.error(f"Amazon search error: {e}")
        return []


def filter_bestbuy_sales(urls: List[str]) -> List[str]:
    """Filter BestBuy URLs to keep only products on sale."""
    return filter_sale_urls(urls)


async def filter_amazon_sales(urls: List[str]) -> List[Tuple[str, dict]]:
    """Filter Amazon URLs to keep only products on sale (requires Playwright)."""
    return await filter_amazon_sale_urls_playwright(urls, headless=False)


async def scrape_bestbuy(urls: List[str]) -> List[ScrapedBestBuyDeal]:
    """Scrape BestBuy product details using Playwright."""
    return await scrape_bestbuy_products(urls, headless=False)


async def scrape_amazon(sale_items: List[Tuple[str, dict]]) -> List[ScrapedAmazonDeal]:
    """Scrape Amazon product details using Playwright."""
    return await scrape_amazon_products(sale_items, headless=False)


def estimate_prices(deal_selection: DealSelection, ensemble_agent: EnsembleAgent) -> List[Opportunity]:
    """
    Estimate prices and calculate discounts.
    
    Args:
        deal_selection: Top deals selected
        ensemble_agent: Initialized EnsembleAgent
    
    Returns:
        List of opportunities sorted by discount (descending)
    """
    opportunities = []
    
    for deal in deal_selection.deals:
        estimate = ensemble_agent.price(deal.product_description)
        discount = estimate - deal.price
        opportunity = Opportunity(
            deal=deal,
            estimate=estimate,
            discount=discount
        )
        opportunities.append(opportunity)
    
    # Sort by discount descending
    opportunities.sort(key=lambda x: x.discount, reverse=True)
    return opportunities


# ============================================================================
# SECTION 9: GRADIO HELPERS
# ============================================================================

class QueueHandler(logging.Handler):
    """Custom logging handler that puts logs into a queue for Gradio."""
    
    def __init__(self, log_queue):
        super().__init__()
        self.log_queue = log_queue

    def emit(self, record):
        self.log_queue.put(self.format(record))


def setup_logging(q):
    """Setup logging to capture all logs into queue."""
    global log_queue
    log_queue = q
    
    handler = QueueHandler(q)
    formatter = logging.Formatter(
        "[%(asctime)s] %(message)s",
        datefmt="%H:%M:%S",
    )
    handler.setFormatter(formatter)
    
    # Add handler to root logger
    logger = logging.getLogger()
    # Remove existing QueueHandlers to avoid duplicates
    for h in logger.handlers[:]:
        if isinstance(h, QueueHandler):
            logger.removeHandler(h)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


def html_for_logs(log_data: List[str]) -> str:
    """Convert log data to HTML for display."""
    # Keep last 25 logs
    recent_logs = log_data[-25:]
    # Format each log with color
    formatted = [reformat(log) for log in recent_logs]
    output = '<br>'.join(formatted)
    return f"""
    <div style="height: 400px; overflow-y: auto; border: 1px solid #444; 
                background-color: #1a1a2e; padding: 10px; font-family: monospace; 
                font-size: 12px; border-radius: 8px;">
    {output}
    </div>
    """


def opportunities_to_table(opportunities: List[Opportunity]) -> list:
    """
    Convert opportunities to data for Gradio Dataframe.
    
    Returns:
        List of rows: [Product, Sale $, Estimate $, Discount $, Discount %, URL]
    """
    rows = []
    for opp in opportunities:
        discount_pct = (opp.discount / opp.estimate * 100) if opp.estimate > 0 else 0
        status = "🔥" if opp.discount > 200 else ("✅" if opp.discount > 100 else ("👍" if opp.discount > 0 else "❌"))
        rows.append([
            opp.deal.product_description[:60] + "...",
            f"${opp.deal.price:.2f}",
            f"${opp.estimate:.2f}",
            f"${opp.discount:.2f}",
            f"{discount_pct:.1f}% {status}",
            opp.deal.url
        ])
    return rows


def format_questions_html(questions: List[ClarificationQuestion]) -> str:
    """Format clarification questions as HTML for display."""
    html = ""
    for i, q in enumerate(questions, 1):
        options_html = ", ".join(q.options)
        html += f"""
        <div style="margin-bottom: 15px; padding: 10px; background: #2a2a4a; border-radius: 8px;">
            <strong style="color: #87CEEB;">Q{i}: {q.question}</strong>
            <br><span style="color: #888; font-size: 0.9em;">Options: {options_html}</span>
        </div>
        """
    return f"""
    <div style="background: #1a1a2e; padding: 15px; border-radius: 10px; border: 1px solid #444;">
        <h4 style="color: #87CEEB; margin-top: 0;">🤖 Clarification Questions</h4>
        {html}
        <p style="color: #888; font-size: 0.85em;">
            💡 Answer these questions below, or click "Skip" to search directly.
        </p>
    </div>
    """


# ============================================================================
# SECTION 10: CLARIFICATION FLOW FUNCTIONS
# ============================================================================

def generate_questions_handler(keyword: str):
    """
    Handle keyword input and generate clarification questions.
    
    Args:
        keyword: User's initial keyword
    
    Returns:
        Tuple: (questions_html, status, show_answers, show_skip)
    """
    global current_questions, current_keyword
    
    if not keyword or len(keyword.strip()) < 2:
        return (
            "",
            "Please enter a keyword (at least 2 characters)",
            gr.update(visible=False),  # answers section
            gr.update(visible=False),  # skip button
        )
    
    try:
        current_keyword = keyword.strip()
        logging.info(f"Generating questions for: {current_keyword}")
        
        response = clarification_agent.generate_questions(current_keyword)
        current_questions = response
        
        questions_html = format_questions_html(response.questions)
        
        return (
            questions_html,
            f"Category: {response.product_category} | Answer the questions below or skip to search directly.",
            gr.update(visible=True),   # Show answers section
            gr.update(visible=True),   # Show skip button
        )
        
    except Exception as e:
        logging.error(f"Error generating questions: {e}")
        return (
            "",
            f"Error: {str(e)}",
            gr.update(visible=False),
            gr.update(visible=False),
        )


def submit_answers_handler(answer1: str, answer2: str, answer3: str, max_urls: int, initial_log_data: List[str]):
    """
    Handle submit answers and run clarification flow.
    
    Yields updates during pipeline execution.
    """
    global current_questions, current_keyword, current_max_urls
    
    if not current_questions:
        yield [], "Please generate questions first!", "", html_for_logs(["Please generate questions first!"])
        return
    
    current_max_urls = int(max_urls) if max_urls else 10
    answers = [answer1.strip(), answer2.strip(), answer3.strip()]
    
    # Build refined query
    try:
        refined = clarification_agent.build_refined_query(
            current_keyword,
            current_questions.questions,
            answers
        )
        search_query = refined.query
        comparison_text = f"🔄 Original: \"{current_keyword}\" → Refined: \"{search_query}\""
    except Exception as e:
        logging.error(f"Error building refined query: {e}")
        search_query = current_keyword
        comparison_text = f"Using original keyword: \"{current_keyword}\""
    
    # Now run the pipeline with refined query
    yield from run_search_pipeline(search_query, comparison_text, initial_log_data)


def skip_and_search_handler(max_urls: int, initial_log_data: List[str]):
    """
    Handle skip button - search with original keyword.
    
    Yields updates during pipeline execution.
    """
    global current_keyword, current_max_urls
    
    if not current_keyword:
        yield [], "Please enter a keyword first!", "", html_for_logs(["Please enter a keyword first!"])
        return
    
    current_max_urls = int(max_urls) if max_urls else 10
    comparison_text = f"⏩ Skip mode - searching with: \"{current_keyword}\""
    
    yield from run_search_pipeline(current_keyword, comparison_text, initial_log_data)


# ============================================================================
# SECTION 11: MAIN SEARCH PIPELINE (MULTI-SOURCE)
# ============================================================================

def do_search_pipeline(search_query: str, max_urls: int, result_queue: queue.Queue):
    """
    Worker function that runs in a separate thread.
    Executes the full MULTI-SOURCE search pipeline and puts result in queue.
    
    This function:
    1. Searches BOTH BestBuy AND Amazon
    2. Filters sale items from both sources
    3. Scrapes products from both sources
    4. Combines into unified pool
    5. GPT selects top 5 from combined pool
    6. EnsembleAgent estimates prices
    
    Args:
        search_query: Search query (refined or original)
        max_urls: Maximum URLs to search PER SOURCE
        result_queue: Queue to put final result
    """
    global current_opportunities
    
    try:
        # ==================== STEP 1: SEARCH BOTH SOURCES ====================
        logging.info(f"🔍 [Step 1/6] Searching '{search_query}' on BestBuy + Amazon...")
        
        # Search in parallel using ThreadPoolExecutor
        bestbuy_urls = []
        amazon_urls = []
        
        with ThreadPoolExecutor(max_workers=2) as executor:
            future_bb = executor.submit(search_bestbuy, search_query, max_urls)
            future_az = executor.submit(search_amazon, search_query, max_urls)
            
            try:
                bestbuy_urls = future_bb.result(timeout=120)
                logging.info(f"  📦 BestBuy: {len(bestbuy_urls)} URLs")
            except Exception as e:
                logging.warning(f"  ⚠️ BestBuy search failed: {e}")
            
            try:
                amazon_urls = future_az.result(timeout=120)
                logging.info(f"  📦 Amazon: {len(amazon_urls)} URLs")
            except Exception as e:
                logging.warning(f"  ⚠️ Amazon search failed: {e}")
        
        if not bestbuy_urls and not amazon_urls:
            result_queue.put(([], "No products found. Try a different keyword."))
            return
        
        logging.info(f"✅ Total URLs: {len(bestbuy_urls)} (BestBuy) + {len(amazon_urls)} (Amazon)")
        
        # ==================== STEP 2: FILTER SALES ====================
        logging.info(f"🏷️ [Step 2/6] Filtering sale items...")
        
        # BestBuy: Uses BeautifulSoup (fast)
        bestbuy_sale_urls = []
        if bestbuy_urls:
            logging.info(f"  🔎 Filtering {len(bestbuy_urls)} BestBuy URLs (BeautifulSoup)...")
            bestbuy_sale_urls = filter_bestbuy_sales(bestbuy_urls)
            logging.info(f"  ✅ BestBuy: {len(bestbuy_sale_urls)} sale items")
        
        # Amazon: Uses Playwright (slower but required)
        amazon_sale_items = []
        if amazon_urls:
            logging.info(f"  🔎 Filtering {len(amazon_urls)} Amazon URLs (Playwright)...")
            
            # Handle async in sync context
            try:
                loop = asyncio.get_event_loop()
            except RuntimeError:
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
            
            amazon_sale_items = loop.run_until_complete(filter_amazon_sales(amazon_urls))
            logging.info(f"  ✅ Amazon: {len(amazon_sale_items)} sale items")
        
        if not bestbuy_sale_urls and not amazon_sale_items:
            result_queue.put(([], "No sale items found. Try a different keyword."))
            return
        
        # ==================== STEP 3: SCRAPE PRODUCTS ====================
        logging.info(f"📦 [Step 3/6] Scraping product details (Playwright)...")
        
        try:
            loop = asyncio.get_event_loop()
        except RuntimeError:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
        
        bestbuy_scraped = []
        amazon_scraped = []
        
        # Scrape BestBuy
        if bestbuy_sale_urls:
            logging.info(f"  🛒 Scraping {len(bestbuy_sale_urls)} BestBuy products...")
            bestbuy_scraped = loop.run_until_complete(scrape_bestbuy(bestbuy_sale_urls))
            logging.info(f"  ✅ BestBuy: Scraped {len(bestbuy_scraped)} products")
        
        # Scrape Amazon
        if amazon_sale_items:
            logging.info(f"  🛒 Scraping {len(amazon_sale_items)} Amazon products...")
            amazon_scraped = loop.run_until_complete(scrape_amazon(amazon_sale_items))
            logging.info(f"  ✅ Amazon: Scraped {len(amazon_scraped)} products")
        
        if not bestbuy_scraped and not amazon_scraped:
            result_queue.put(([], "Could not scrape product details."))
            return
        
        # ==================== STEP 4: COMBINE INTO UNIFIED POOL ====================
        logging.info(f"🔀 [Step 4/6] Combining products from both sources...")
        
        unified_deals = []
        
        for deal in bestbuy_scraped:
            unified_deals.append(UnifiedScrapedDeal.from_bestbuy(deal))
        
        for deal in amazon_scraped:
            unified_deals.append(UnifiedScrapedDeal.from_amazon(deal))
        
        logging.info(f"✅ Combined pool: {len(unified_deals)} products ({len(bestbuy_scraped)} BestBuy + {len(amazon_scraped)} Amazon)")
        
        # ==================== STEP 5: SELECT TOP 5 ====================
        logging.info(f"🤖 [Step 5/6] GPT selecting top 5 from combined pool...")
        
        deal_selection = multi_scanner.scan(unified_deals)
        
        if not deal_selection or not deal_selection.deals:
            result_queue.put(([], "Could not select deals."))
            return
        
        logging.info(f"✅ Selected {len(deal_selection.deals)} best deals")
        
        # ==================== STEP 6: ESTIMATE PRICES ====================
        logging.info(f"💰 [Step 6/6] Estimating prices with EnsembleAgent (3 models)...")
        
        opportunities = estimate_prices(deal_selection, ensemble)
        current_opportunities = opportunities  # Save for push notification
        
        logging.info(f"✅ Estimated {len(opportunities)} opportunities")
        
        if opportunities:
            best = opportunities[0]
            logging.info(f"🏆 BEST DEAL: ${best.deal.price:.2f} → Est: ${best.estimate:.2f} = Discount ${best.discount:.2f}")
        
        # Return results
        table = opportunities_to_table(opportunities)
        status = f"✅ Found {len(opportunities)} deals! Best discount: ${opportunities[0].discount:.2f}" if opportunities else "No deals found."
        
        result_queue.put((table, status))
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        result_queue.put(([], f"Error: {str(e)}"))


def run_search_pipeline(search_query: str, comparison_text: str, initial_log_data: List[str]):
    """
    Generator function for Gradio that yields updates during pipeline execution.
    
    Args:
        search_query: The query to search (refined or original)
        comparison_text: Text showing original vs refined query
        initial_log_data: Previous log data
    
    Yields:
        Tuple of (table_data, status_text, comparison_html, logs_html)
    """
    global current_max_urls
    max_urls = current_max_urls if current_max_urls else 10
    
    # Setup
    log_q = queue.Queue()
    result_q = queue.Queue()
    setup_logging(log_q)
    
    log_data = initial_log_data.copy() if initial_log_data else []
    log_data.append(f"🚀 Starting MULTI-SOURCE search: {search_query} (max {max_urls} URLs per source)")
    log_data.append("📦 Sources: BestBuy + Amazon")
    
    # Start worker thread
    thread = threading.Thread(
        target=do_search_pipeline,
        args=(search_query, max_urls, result_q)
    )
    thread.start()
    
    # Yield updates while thread is running
    final_result = None
    while thread.is_alive() or not log_q.empty() or final_result is None:
        # Check for new logs
        try:
            while True:
                message = log_q.get_nowait()
                log_data.append(message)
        except queue.Empty:
            pass
        
        # Check for result
        try:
            final_result = result_q.get_nowait()
        except queue.Empty:
            pass
        
        # Yield current state (with HTML logs)
        if final_result:
            table, status = final_result
            yield table, status, comparison_text, html_for_logs(log_data)
        else:
            yield [], "⏳ Processing...", comparison_text, html_for_logs(log_data)
        
        time.sleep(0.1)
    
    # Final yield
    if final_result:
        table, status = final_result
        log_data.append(f"✅ Pipeline completed!")
        yield table, status, comparison_text, html_for_logs(log_data)


# ============================================================================
# SECTION 12: PUSH NOTIFICATION
# ============================================================================

def send_push_notification(selected_index: int) -> str:
    """
    Send push notification for selected deal.
    
    Args:
        selected_index: Index of deal in table (0-based)
    
    Returns:
        Status message
    """
    global current_opportunities
    
    if not current_opportunities:
        return "No deals available. Search first!"
    
    idx = int(selected_index)
    if idx < 0 or idx >= len(current_opportunities):
        return f"Invalid selection. Choose 0-{len(current_opportunities)-1}"
    
    opp = current_opportunities[idx]
    
    try:
        messenger.notify(
            description=opp.deal.product_description[:200],
            deal_price=opp.deal.price,
            estimated_true_value=opp.estimate,
            url=opp.deal.url
        )
        return f"✅ Sent! Deal #{idx}: {opp.deal.product_description[:40]}... (${opp.deal.price:.2f})"
    except Exception as e:
        return f"Failed: {str(e)}"


# ============================================================================
# SECTION 13: GRADIO UI DEFINITION
# ============================================================================

def create_gradio_app():
    """Create and return Gradio app with multi-source search and clarification flow."""
    
    with gr.Blocks(
        title="Multi-Source Deal Finder",
        theme=gr.themes.Soft(),
        fill_width=True,
    ) as app:
        
        # State for logs
        log_data_state = gr.State([])
        
        # Header
        gr.Markdown("""
        # 🛒 Multi-Source Deal Finder v3
        
        Search on **BOTH** BestBuy AND Amazon simultaneously!
        
        **New Flow:** 
        1️⃣ Enter Keyword → 2️⃣ Answer Questions (or Skip) → 3️⃣ Search BestBuy + Amazon → 4️⃣ Estimate Prices
        
        ⚠️ **Note:** Browser windows will open for Playwright scraping (Amazon requires this).
        """)
        
        # ==================== STEP 1: KEYWORD INPUT ====================
        with gr.Group():
            gr.Markdown("### 📝 Step 1: Enter Product Keyword")
            with gr.Row():
                keyword_input = gr.Textbox(
                    label="🔎 What are you looking for?",
                    placeholder="Enter product keyword (e.g., laptop, Smart TV, headphones)",
                    scale=3
                )
                max_urls_input = gr.Number(
                    label="Max URLs (per source)",
                    value=10,
                    minimum=5,
                    maximum=20,
                    precision=0,
                    scale=1
                )
                generate_btn = gr.Button("🤖 Generate Questions", variant="primary", scale=1)
        
        # Status message
        status_text = gr.Textbox(
            label="Status",
            interactive=False,
            value="Enter a keyword and click 'Generate Questions'"
        )
        
        # ==================== STEP 2: CLARIFICATION QUESTIONS ====================
        with gr.Group() as questions_section:
            questions_html = gr.HTML(
                value='<div style="padding: 20px; text-align: center; color: #888;">Questions will appear here after you enter a keyword...</div>'
            )
        
        # ==================== STEP 3: ANSWERS INPUT ====================
        with gr.Group(visible=False) as answers_section:
            gr.Markdown("### ✍️ Step 2: Answer the Questions")
            gr.Markdown("*Type your answers freely (e.g., 'Acer', 'for students', 'under $800') or use options above*")
            
            with gr.Row():
                answer1 = gr.Textbox(label="Answer 1", placeholder="Your answer to Q1...")
                answer2 = gr.Textbox(label="Answer 2", placeholder="Your answer to Q2...")
                answer3 = gr.Textbox(label="Answer 3", placeholder="Your answer to Q3...")
            
            with gr.Row():
                submit_btn = gr.Button("✅ Submit & Search (BestBuy + Amazon)", variant="primary", scale=2)
                skip_btn = gr.Button("⏩ Skip, Search Now", variant="secondary", scale=1)
        
        # ==================== QUERY COMPARISON ====================
        query_comparison = gr.Textbox(
            label="🔄 Query Comparison",
            interactive=False,
            visible=True,
            placeholder="Original vs Refined query will appear here..."
        )
        
        # ==================== RESULTS ====================
        with gr.Row():
            # Left: Results Table
            with gr.Column(scale=3):
                gr.Markdown("### 🏆 Deal Results (BestBuy + Amazon combined)")
                results_table = gr.Dataframe(
                    headers=["Product", "Sale $", "Estimate $", "Discount $", "Discount %", "URL"],
                    label="Sorted by discount (best first)",
                    wrap=True,
                    column_widths=[4, 1, 1, 1, 1, 2],
                    max_height=350,
                )
            
            # Right: Real-time Logs
            with gr.Column(scale=2):
                gr.Markdown("### 📋 Pipeline Logs")
                logs_html = gr.HTML(
                    value='<div style="height: 400px; background-color: #1a1a2e; border-radius: 8px; padding: 10px; font-family: monospace; color: #87CEEB;">Ready to search...</div>'
                )
        
        # ==================== PUSH NOTIFICATION ====================
        with gr.Row():
            deal_index = gr.Number(
                label="Deal # to notify (0 = best deal)",
                value=0,
                minimum=0,
                precision=0,
                scale=1
            )
            push_btn = gr.Button("📱 Send Push Notification", variant="secondary", scale=1)
        
        push_status = gr.Textbox(
            label="📱 Notification Status",
            interactive=False,
            placeholder="Click 'Send Push Notification' to send...",
            lines=2,
        )
        
        # ==================== EVENT HANDLERS ====================
        
        # Generate questions
        generate_btn.click(
            fn=generate_questions_handler,
            inputs=[keyword_input],
            outputs=[questions_html, status_text, answers_section, answers_section],
        )
        
        # Submit answers and search
        submit_btn.click(
            fn=submit_answers_handler,
            inputs=[answer1, answer2, answer3, max_urls_input, log_data_state],
            outputs=[results_table, status_text, query_comparison, logs_html],
        )
        
        # Skip and search directly
        skip_btn.click(
            fn=skip_and_search_handler,
            inputs=[max_urls_input, log_data_state],
            outputs=[results_table, status_text, query_comparison, logs_html],
        )
        
        # Push notification
        push_btn.click(
            fn=send_push_notification,
            inputs=[deal_index],
            outputs=[push_status],
        )
        
        # Footer
        gr.Markdown("""
        ---
        **Legend:** 🔥 Discount > $200 | ✅ Discount > $100 | 👍 Positive discount | ❌ Overpriced
        
        **Sources:** 
        - 🟦 BestBuy: Filter uses BeautifulSoup, scrape uses Playwright
        - 🟠 Amazon: Both filter and scrape use Playwright (Amazon blocks requests)
        
        **Notes:** 
        - Browser windows will open during Amazon operations
        - Push notifications require Pushover setup
        """)
    
    return app


# ============================================================================
# SECTION 14: MAIN ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("🚀 Multi-Source Deal Finder v3 - Starting up...")
    print("   Sources: BestBuy + Amazon")
    print("=" * 60)
    
    # Initialize agents (this may take 5-10 seconds)
    init_agents()
    
    # Create and launch Gradio app
    app = create_gradio_app()
    
    print("\n" + "=" * 60)
    print("✅ Ready! Opening browser...")
    print("=" * 60 + "\n")
    
    app.launch(share=False, inbrowser=True)
